language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "pypy"
install:
    - pip install flake8 --use-mirrors
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 --use-mirrors; fi"
script:
    - test/run_tests.sh
notifications:
    email:
        - deniscostadsc@gmail.com