language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"
install:
    - pip install -r requirements_test.txt --use-mirrors
script:
    - tests/run_tests.sh
notifications:
    email:
        - deniscostadsc@gmail.com
